spring:
  datasource:
    url: jdbc:h2:mem:classroomdb;MODE=LEGACY;DATABASE_TO_LOWER=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS classroom;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  application:
    name: classroom-service

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true

server:
  port: 8083
  servlet:
    context-path: /classroom-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: DEBUG

# auth service
users:
  service:
    url: http://AUTH-SERVICE/users
    user-exist-url: ${users.service.url}/exist
    internal-secret: CaNipXZWYxzx2Buah8xyaFiAUunRJMFB